headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "D:\\DGStudio projects\\angular-portfolio-project2\\docs"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build:prod"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "*.js"

[headers.values]
Content-Type = "application/javascript; charset=utf-8"
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.css"

[headers.values]
Content-Type = "text/css; charset=utf-8"
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.json"

[headers.values]
Content-Type = "application/json; charset=utf-8"

[[headers]]
for = "/*.ico"

[headers.values]
Content-Type = "image/x-icon"

[[headers]]
for = "/*.png"

[headers.values]
Content-Type = "image/png"

[[headers]]
for = "/*.webp"

[headers.values]
Content-Type = "image/webp"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]