[build]
  publish = "docs"
  command = "npm run build:prod"

# Headers для MIME-типов
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Content-Type = "image/x-icon"

[[headers]]
  for = "/*.png"
  [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Content-Type = "image/webp"

# SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
